finance/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name = 'finance-home'),
]

personal_finance_tracker/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name = 'register'),
    path('profile/', user_views.profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('', include('finance.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class Group(models.Model):
    host = models.ForeignKey(User, default = 'Deleted host', on_delete = models.SET_DEFAULT)
    code = models.CharField(max_length = 100)
    name = models.CharField(max_length = 50, default=None)
    created_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name

class SharedTransaction(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    payer = models.ForeignKey(User, default = 'Deleted user', on_delete = models.SET_DEFAULT)
    item = models.CharField(max_length = 100)
    account = models.CharField(max_length=25, default = 'card')
    category = models.CharField(max_length = 50)
    amount = models.FloatField()
    content = models.TextField(null = True)
    transaction_date = models.DateTimeField()

    def __str__(self):
        return f'{self.category} - {self.item} - {self.transaction_date.strftime("%Y-%m-%d %H:%M:%S")}'

class Transaction(models.Model):
    payer = models.ForeignKey(User, on_delete = models.CASCADE)
    item = models.CharField(max_length = 100)
    account = models.CharField(max_length=25, default = 'card')
    category = models.CharField(max_length = 50)
    amount = models.FloatField()
    content = models.TextField(null = True)
    transaction_date = models.DateTimeField()

    def __str__(self):
        return f'{self.category} - {self.item} - {self.transaction_date.strftime("%Y-%m-%d %H:%M:%S")}'

finance/forms.py
from django import forms
from .models import Transaction
import datetime

ACCOUNT = [('Cash', 'Cash'), ('Accounts','Accounts'), ('Card', 'Card')]

CATEGORIES= [
    ('Food', 'Food'),
    ('Social Life', 'Social Life'),
    ('Self-development', 'Self-development'),
    ('Transportation', 'Transportation'),
    ('Culture', 'Culture'),
    ('Household', 'Household'),
    ('Apparel', 'Apparel'),
    ('Beauty', 'Beauty'),
    ('Health', 'Health'),
    ('Education', 'Education'),
    ('Gift', 'Gift'),
    ('Other', 'Other'),
]

class TransactionCreateForm(forms.ModelForm):
    account = forms.CharField(widget=forms.Select(choices=ACCOUNT))
    category = forms.CharField(widget=forms.Select(choices=CATEGORIES))
    transaction_date = forms.DateTimeField(initial=datetime.datetime.today)
    class Meta:
        model = Transaction
        exclude = ['payer']

finance/views.py
from django.shortcuts import render, redirect
from django.db.models import Sum
from .models import Transaction
from datetime import datetime
from django.contrib.auth.decorators import login_required
from .forms import TransactionCreateForm
from django.contrib import messages

@login_required
def home(request):
    '''
        In home page, the personal tab opens up. Here, the intention is to show the categories of expenses available for the
        current year and month. In addition, the total expenses incurred for the current year for all months will be identified too.
        Apart from visuals, the user should perform CRUD operations on the personal tab as well as the group tab.
        The figures on visuals and transaction events will change when the user wishes to choose a different year and month
        for querying. The aforementioned intention and logic will be applied to the Group tab soon.
        This will be performed in a different function since the home page is all about initialization and setup.
    '''
    category_labels = []
    category_data = []
    total_monthly_expenses = []
    months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    current_year = datetime.now().date().year
    current_month = datetime.now().date().month
    current_year_transactions = Transaction.objects.filter(payer = request.user, transaction_date__year=current_year)
    transactions = current_year_transactions.filter(transaction_date__month=current_month)

    total = transactions.aggregate(Sum('amount'))
    category_list = (transactions.values('category').distinct())

    for month in months:
        monthly_expense = current_year_transactions.filter(transaction_date__month=month).aggregate(Sum('amount'))
        #need to render the visuals, None is not accepted in frontend hence converting all None values to 0
        if monthly_expense['amount__sum'] is None:
            monthly_expense['amount__sum'] = 0
        total_monthly_expenses.append(monthly_expense['amount__sum'])

    for item in category_list:
        category_labels.append(item['category'])
        category_amount = transactions.filter(category = item['category']).aggregate(Sum('amount'))
        category_amount = (category_amount['amount__sum'] / total['amount__sum']) * 100
        category_ratio = round(category_amount, 2)
        category_data.append(category_ratio)

    if (request.method == 'POST'):
        form = TransactionCreateForm(request.POST, instance=request.user)
        if form.is_valid():
            #form data is not being saved, figure out why
            data = form.save(commit=False)
            data.payer = request.user
            data.save()
            print(data.cleaned_data)
            messages.success(request, f'Your first transaction is created!')
            return redirect('finance-home')
    else:
        form = TransactionCreateForm(instance=request.user)

    context = {
        'transactions': transactions,
        'category_labels': category_labels,
        'category_data': category_data,
        'total_monthly_expenses': total_monthly_expenses,
        'form': form,
    }
    return render(request, 'finance/home.html', context)

finance/templates/finance/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel = "stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'finance/main.css' %}">
    <title>Manage finances easily!</title>
</head>
<body>
    <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'finance-home' %}">TrackIt<i class="fa-solid fa-calculator ms-2"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'finance-home' %}">Home</a>
            <!-- <a class="nav-item nav-link" href="/about">About</a> -->
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
            </div>
        </div>
        </div>
    </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>  
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>  
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>
</body>
</html>

finance/templates/finance/home.html
{% extends "finance/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if transactions %}
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" data-bs-toggle="tab" href="#personal">Personal</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#family">Family</a>
            </li>
        </ul>

        <div class="tab-content">
            <div id="personal" class="tab-pane fade show active">
                <div class="row">
                    <div class="col-md-6">
                        <canvas id="categorySplit"></canvas>
                    </div>
                    <div class="col-md-5">
                        <canvas id="totalMonthlyExpenditure"></canvas>
                    </div>
                </div>

                <table class="table">
                    <thead>
                        <button type="button" class="btn btn-success">Add</button>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item</th>
                            <th scope="col">Category</th>
                            <th scope="col">Description</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Date</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for transaction in transactions %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ transaction.item }}</td>
                            <td>{{ transaction.category }}</td>
                            {% if transaction.content %}
                                <td>{{ transaction.content }}</td>
                            {% else %}
                                <td> - </td>
                            {% endif %}
                            <td>{{ transaction.amount }}</td>
                            <td>{{ transaction.transaction_date|date:"F d, Y H:s a" }}</td>
                            <td><button type="button" class="btn btn-info">Edit</button></td>
                            <td><button type="button" class="btn btn-danger">Delete</button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div id="family" class="tab-pane fade">
                <p>Coming soon!</p>
            </div>
        </div>


        <!-- Javascript render below for all, what about segregration of javascript code between personal and family? -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
            <script>
            const totalMonthlyExpenditure = document.getElementById('totalMonthlyExpenditure');
            const categorySplit = document.getElementById('categorySplit');
            // const ctx = document.getElementById('totalMonthlyExpenditure');


            new Chart(totalMonthlyExpenditure, {
                type: 'bar',
                data: {
                    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                    datasets: [{
                    label: 'Accumulated expense per month',
                    data: {{ total_monthly_expenses|safe }},
                    borderWidth: 2
                    }]
                },
                options: {
                    maintainAspectRatio: false,
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });

            new Chart(categorySplit, {
                type: 'pie',
                data: {
                    labels: {{ category_labels|safe }},
                    datasets: [{
                        label: 'Expense Breakup - current month',
                        data: {{ category_data|safe }},
                        backgroundColor: [
                        'rgb(255, 99, 132)',
                        'rgb(54, 162, 235)',
                        'rgb(255, 205, 86)',
                        'rgb(255, 99, 132)',
                        'rgb(54, 162, 235)',
                        'rgb(255, 205, 86)',
                        'rgb(255, 205, 86)'
                        ],
                        hoverOffset: 4
                    }]
                },
                options: {
                    maintainAspectRatio: false
                }
            });
        </script>
    {% else %}
        <div class="container">
            <form method = "POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Add transaction</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit"> Add </button>
                </div>
            </form>
        </div>
    {% endif %}
    <script>
        $(function() {  
            $('#id_transaction_date').datetimepicker();  
        });  
    </script>
{% endblock content %}